// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhVOH-ZcFyz7EJNNnq9etnI5gArDW1TyM',
    appId: '1:945149119735:web:f68c991cf06d7ee15ad7f2',
    messagingSenderId: '945149119735',
    projectId: 'gerenciamento-thorp',
    authDomain: 'gerenciamento-thorp.firebaseapp.com',
    storageBucket: 'gerenciamento-thorp.appspot.com',
    measurementId: 'G-8P4HNNKCGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVVNwWnaRPhi1HBKNr0zXcB19diHwcn8',
    appId: '1:945149119735:android:33f8347dab22ea875ad7f2',
    messagingSenderId: '945149119735',
    projectId: 'gerenciamento-thorp',
    storageBucket: 'gerenciamento-thorp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1oqaXsGQuZu3GRAX1X0gVF_S_mUQKQPc',
    appId: '1:945149119735:ios:9a9de1375c5d438a5ad7f2',
    messagingSenderId: '945149119735',
    projectId: 'gerenciamento-thorp',
    storageBucket: 'gerenciamento-thorp.appspot.com',
    iosClientId: '945149119735-cchme0f6iglledkl6jl4q8ferol9rvcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.thorpGerenciamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1oqaXsGQuZu3GRAX1X0gVF_S_mUQKQPc',
    appId: '1:945149119735:ios:9a9de1375c5d438a5ad7f2',
    messagingSenderId: '945149119735',
    projectId: 'gerenciamento-thorp',
    storageBucket: 'gerenciamento-thorp.appspot.com',
    iosClientId: '945149119735-cchme0f6iglledkl6jl4q8ferol9rvcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.thorpGerenciamento',
  );
}
