// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ignore: depend_on_referenced_packages

// ...

// ignore: non_constant_identifier_names

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzRS6oJZ0-5z8n2yaFuQmYCTZ9T5ZcGXE',
    appId: '1:217833603542:web:a5fc89bde698585e652477',
    messagingSenderId: '217833603542',
    projectId: 'chat-4c646',
    authDomain: 'chat-4c646.firebaseapp.com',
    storageBucket: 'chat-4c646.appspot.com',
    measurementId: 'G-ZPHDMTRHY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTvcJpA0o5DNoszddlFZIQrTFzubiHcM',
    appId: '1:217833603542:android:32bc1059c23748a6652477',
    messagingSenderId: '217833603542',
    projectId: 'chat-4c646',
    storageBucket: 'chat-4c646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwcunN-W3Wd12DhCVzFwilzIQsS5WORI',
    appId: '1:217833603542:ios:86e471cd52de4499652477',
    messagingSenderId: '217833603542',
    projectId: 'chat-4c646',
    storageBucket: 'chat-4c646.appspot.com',
    iosClientId:
        '217833603542-gpctr4f76djmvpisu2m8nm2664d61dq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwcunN-W3Wd12DhCVzFwilzIQsS5WORI',
    appId: '1:217833603542:ios:86e471cd52de4499652477',
    messagingSenderId: '217833603542',
    projectId: 'chat-4c646',
    storageBucket: 'chat-4c646.appspot.com',
    iosClientId:
        '217833603542-gpctr4f76djmvpisu2m8nm2664d61dq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
