// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyz1S3QkCodJHinCLxMjXDx8JHOWo19w',
    appId: '1:644225959180:web:6c709dcdde6358f1f2b529',
    messagingSenderId: '644225959180',
    projectId: 'thicos-60bce',
    authDomain: 'thicos-60bce.firebaseapp.com',
    databaseURL: 'https://thicos-60bce-default-rtdb.firebaseio.com',
    storageBucket: 'thicos-60bce.appspot.com',
    measurementId: 'G-KMV3FQJFLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpULta-dVb9oix8vTLE15KXDuw0shHCgE',
    appId: '1:644225959180:android:6e063fff9cc3c342f2b529',
    messagingSenderId: '644225959180',
    projectId: 'thicos-60bce',
    databaseURL: 'https://thicos-60bce-default-rtdb.firebaseio.com',
    storageBucket: 'thicos-60bce.appspot.com',
  );
}
